procees 1 et 2
sahamone/ocr pull request #13
Opened 2024-12-05 16:21 UTC by noeblp

2024-12-05 16:24 UTC, Napoleon280 requested changes
Fix proccessor.c

2024-12-05 16:24 UTC, Napoleon280 commented on UI/processor.c
> +void run_neural(int set)
This needs to be fixed, duplicate

2024-12-05 16:25 UTC, Napoleon280 commented on UI/processor.c
> +void run_neural(int set)
And use or removed param

2024-12-06 07:08 UTC, closed without merging

2024-12-06 07:08 UTC, sahamone commented
Not good